apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-postgres
  labels:
    type: local
    name: volume-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 200M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-claim-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200M